# Copyright 2015, Pablo Ridolfi
#
# This file is part of uPOSIX.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# +---------------------------------------------------------------------------+
# | DO NOT MODIFY THIS FILE!                                                  |
# +---------------------------------------------------------------------------+
# You should make a copy of this file named Makefile.mine and modify PROJECT
# and TARGET variables according to your preferences.
# Happy coding! :-)

# Project location, relative to uPOSIX path.
PROJECT := examples/blinky

# Target processor:
# +---------+-----------------------------------------------------------------+
# | TARGET  |  Description                                                    |
# +---------+-----------------------------------------------------------------+
# | lpc1769 |  NXP LPC1769 Cortex-M3 microcontroller.                         |
# +---------+-----------------------------------------------------------------+
# | lpc4337 |  NXP LPC4337 Cortex-M4/M0 dual-core microcontroller.            |
# +---------+-----------------------------------------------------------------+
TARGET := lpc1769
